---
- hosts: jenkins
  gather_facts: yes

  vars_files:
    - vars/main.yml

  tasks:
    apt: name=libsqlite3-dev state=present

  roles:
    - geerlingguy.firewall
    - geerlingguy.ntp
    - geerlingguy.git
    - geerlingguy.java
    - geerlingguy.jenkins
    - role: znzj.rbenv
      rbenv_ruby_version: 2.2.2
    - packages

